---
title: "First Knit"
author: "Kelly Acevedo"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I went to Roybal Learning Center for High School which is located in Downtown LA. I graduated in 2021 right after Covid.I think for me English class is the most easiest class to me than math because I had always struggle in math class however I try my best to push it to my limit because trying is what matters.The best subject I done would be Science because it always been the easiest to learn about and the class I less struggled because I am good at memorizing information and since im a visual learned there's always a demostration right after the lesson.  

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
 I owned an Apple computer and since im very comfortable with it I would say my knowledge of doing computer things would be a 9 depending of what we are doing.I definitely have access to internet access anywhere since with apple everything is connected I can always share my connection with the item and the connection itself is good where I live. 
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
   I don't have any preference towards my name so going by just Kelly is completely fine.

 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
      
I'm looking forward to achieve in life the knowledge of being able to help my community and by this is getting a doctorate in Psychology.The reason behind its because I want to focus that everyone gets the right resources and help them.
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
I had never gone to a foreign country however I did take a break of two years before I got back to school to travel around a few state because my main goal is to spend time in every other state and afterwards travel outside the country because believe me there are so many nice places here in the US for example Philly,New Jersey,New York,Arizona,Seattle,Texas which are just a few places I been to.California itself has nice places for example San Francisco which is full of very interesting history every single corner you turn too,San Diego has the best hiking paths for example when I went I was part of a five hour bike trip.However One of my main goals in going to Jerusalem or Japan because they both have very pretty landscaping and their culture is very interesting and pretty.

   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   Im takin statitics because during high school I took pre-calculus as one of my highest math since I did take algebra and geometry with high greats and im taking stats as a requirement now.However I am good at memorizing and learning so hopefully I pass this class with a graded that wont affect my plans.I'm planning on going out my comfort zone and ask questions when I truly don't understand and of course not being afraid of trying because if I don't I wont know how to understand something.
   
 
 






  




